name: ASYNC-RDMA-CI
on:
  pull_request:
    branches: [master]

env:
  CI_RUST_TOOLCHAIN: 1.50.0

jobs:
  soft-roce-env:
    name: Env test for soft-roce and softiwarp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ env.CI_RUST_TOOLCHAIN }}
          override: true
      - name: Run
        run: |
          sudo apt-get install -y net-tools librdmacm-dev ibverbs-utils rdmacm-utils perftest
          ./scripts/run.sh
      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3

