name: ASYNC-RDMA-CI
on:
  pull_request:
    branches: [master]
  schedule: [cron: "0 */24 * * *"]

env:
  CI_RUST_TOOLCHAIN: 1.63.0

jobs:
  soft-roce-env:
    name: Env test for soft-roce and softiwarp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Git Sumbodule Update
        run: |
          git submodule update --remote --recursive
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ env.CI_RUST_TOOLCHAIN }}
          override: true
      - name: Run
        run: |
          sudo apt update
          sudo apt install -y net-tools librdmacm-dev ibverbs-utils rdmacm-utils perftest
          ./rdma-env-setup/scripts/setup.sh
          ./scripts/run.sh  ${{ env.CI_RUST_TOOLCHAIN }}
      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Install CSI dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake g++ libprotobuf-dev protobuf-compiler
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ env.CI_RUST_TOOLCHAIN }}
          override: true
      - run: |
          sudo apt-get install -y librdmacm-dev ibverbs-utils rdmacm-utils
          rustup component add clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-features --all-targets -- -D warnings

  fmt:
    name: Fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ env.CI_RUST_TOOLCHAIN }}
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
